name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install python-pip
        pip install -r requirements.txt
        python download_user_album.py unsplash all raw

    - uses: actions/upload-artifact@master
      with:
        name: wallpapers
        path: /
